Netmask validation updated

diff --git a/install b/install
--- a/install
+++ b/install
@@ -264,25 +264,15 @@ function valid_ip(){
 }
 
 function validate_netmask(){
-    local netmask=$1
-    local netmask_binary
-    local octet
-    local stat
 
-    if [[ $netmask =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
-        stat=0
-        for ((i=0; i<4; i++))
-        do
-            octet=${netmask%%.*}
-            netmask=${netmask#*.}
-            [[ $octet -gt 255 ]] && { stat=1; break; }
-            netmask_binary=$netmask_binary$( echo "obase=2; $octet" | bc )
-            [[ $netmask_binary =~ 01 ]] && { stat=1; break; }
-        done
-    else
-        stat=1
-    fi
-    return $stat
+   echo $1 | grep -w -E -o '^(254|252|248|240|224|192|128)\.0\.0\.0|255\.(254|252|248|240|224|192|128|0)\.0\.0|255\.255\.(254|252|248|240|224|192|128|0)\.0|255\.255\.255\.(254|252|248|240|224|192|128|0)' > /dev/null
+   if [ $? -eq 0 ]; then
+      return 0;
+   else
+      return 1;
+   fi
+   ##Better version
+   ##grep -E -q '^(254|252|248|240|224|192|128)\.0\.0\.0|255\.(254|252|248|240|224|192|128|0)\.0\.0|255\.255\.(254|252|248|240|224|192|128|0)\.0|255\.255\.255\.(254|252|248|240|224|192|128|0)' <<< "$1" && echo "Valid netmask" || echo "Invalid netmask"
 }
 
 
